// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type InputID struct {
	ID int `json:"id"`
}

type NewCategory struct {
	Name string `json:"name"`
}

type NewProduct struct {
	Name       string   `json:"name"`
	Desc       *string  `json:"desc"`
	Picture    *string  `json:"picture"`
	Price      int      `json:"price"`
	Category   *InputID `json:"category"`
	Wscost     int      `json:"wscost"`
	NumOfSides *int     `json:"num_of_sides"`
}
