[Logging]
Enabled = true
EnableHTTP = true
Level = "debug"

[Database]
Address = "pos-database"
Username = "root"
Password = "password"
Name = "koala-pos"

[Webserver]
Port = 8080

[Auth]
SigningKey = ""
