version: "3.6"
services:
  pos-backend:
    image: alpine:edge
    container_name: "pos-backend"
    depends_on:
      - pos-database
    links:
      - pos-database
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ../bin/koala-pos:/app/koala-pos
      - ../logs:/app/logs
    ports:
      - 8080:8080
    working_dir: /app
    command: /app/koala-pos -c /app/config.toml -d

  pos-database:
    image: mariadb:latest
    container_name: "pos-database"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: koala-pos
    volumes:
      - pos-db-data:/var/lib/mysql
    command: mysqld --ansi --sql-mode=ANSI,TRADITIONAL

volumes:
  pos-db-data:
